### PR TITLE
Remove client-side LESS support

### PR DESCRIPTION
**Pull request by gauthierm**
https://trello.com/c/K6ZL3ask/35-remove-client-side-less-fallback

### CODE REVIEW

**Comment by m-mitchell** [comment]
Is there still a purpose for the $compile parameter and the setting in the ini files? It seems like you would never want to pass `$compile=false` since it won't link any styles.

**Comment by gauthierm** [comment]
> Is there still a purpose for the $compile parameter and the setting in the ini files? It seems like you would never want to pass $compile=false since it won't link any styles. 

Good point. I'll drop that config.

**Comment by m-mitchell** [comment]
Do we also need to fix up where we call the code? 

https://github.com/silverorange/site/blob/ff30065c8111a463bb9302d31087508a3930e569/Site/layouts/SiteLayout.php#L310

And do we want to remove the ini setting?

**Comment by gauthierm** [comment]
> Do we also need to fix up where we call the code?

Yep. Will need an additional PR in Site package.

**Comment by gauthierm** [comment]
https://github.com/silverorange/site/pull/280

**Comment by gauthierm** [comment]
https://app.clubhouse.io/silverorangeinc/story/3057/remove-client-side-less-fallback

**Pull request merged**
