### PR TITLE
Allow adding replicators after init

### PR DESCRIPTION
**Pull request by nburka**
Allows initializing the form with values before the form is submitted.

### CODE REVIEW

**Comment by gauthierm** [comment]
What's the use-case for this? If you add a replicator after init it won't have an embedded widget created.

**Comment by nburka** [comment]
> What's the use-case for this? If you add a replicator after init it won't have an embedded widget created.

This is used for initing the form with values already set in the replication.

**Comment by charleswaddell** [comment]
This change will need to be made to a fork of swat `2.2.0 <2.4.0` if we want to use this on EM:RAP.

**Comment by nburka** [comment]
> This change will need to be made to a fork of swat 2.2.0 <2.4.0 if we want to use this on EM:RAP.

See https://github.com/silverorange/swat/pull/81

**Pull request merged**
